---
record_0:
  Title: Registration
  Start time: 10/16/2013 9:00
  Stop time: 10/16/2013 9:30
  Room: ' - '
  Abstract: "08:30-08:35\tMC opening"
  Column span: '7'
  Position: '1'
  Row span: '1'
  Background color: '#dddbdb'
  Speakers: ' -'
record_1:
  Title: Opening
  Start time: 10/16/2013 9:30
  Stop time: 10/16/2013 10:15
  Room: Ballroom B
  Abstract: ' - '
  Column span: '7'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: ' Peter Lundin and Lars Frank'
record_2:
  Title: Fearless Change
  Start time: 10/16/2013 10:15
  Stop time: 10/16/2013 11:45
  Room: Ballroom B
  Abstract: ' - '
  Column span: '7'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: Linda Rising
record_3:
  Title: Lunch
  Start time: 10/16/2013 11:45
  Stop time: 10/16/2013 13:00
  Column span: '7'
  Position: '1'
  Row span: '1'
  Background color: ' - '
record_4:
  Title: A Journey to Delight Customer Embrace Lean and Agile
  Start time: 10/16/2013 13:00
  Stop time: 10/16/2013 14:00
  Room: ROOM 101
  Abstract: activity abstract
  Column span: '2'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: Herry Qiao
record_5:
  Title: Experiencing KANABN and continuously improving customer's satisfaction
  Start time: 10/16/2013 13:00
  Stop time: 10/16/2013 14:00
  Room: ROOM 102
  Abstract: activity abstract
  Column span: '2'
  Position: '2'
  Row span: '2'
  Background color: ' - '
  Speakers: Tom Tan X
record_6:
  Title: Environment Driven Development
  Start time: 10/16/2013 13:00
  Stop time: 10/16/2013 14:00
  Room: ROOM 103
  Abstract: activity abstract
  Column span: '2'
  Position: '3'
  Row span: '2'
  Background color: ' - '
  Speakers: Weijia Lu
record_7:
  Title: Make Agile journey smooth by leveraging in-house developed CI framework
  Start time: 10/16/2013 13:00
  Stop time: 10/16/2013 14:00
  Room: ROOM 104
  Abstract: activity abstract
  Column span: '2'
  Position: '4'
  Row span: '2'
  Background color: ' - '
  Speakers: Ke Li
record_8:
  Title: Best Practices On Gerrit Based Code Review
  Start time: 10/16/2013 13:00
  Stop time: 10/16/2013 14:00
  Room: ROOM 105
  Abstract: activity abstract
  Column span: '2'
  Position: '5'
  Row span: '2'
  Background color: ' - '
  Speakers: Vivian Yang W
record_9:
  Title: Bitterness and Happiness in Agile Journey
  Start time: 10/16/2013 13:00
  Stop time: 10/16/2013 14:00
  Room: ROOM 106
  Abstract: activity abstract
  Column span: '2'
  Position: '6'
  Row span: '2'
  Background color: ' - '
  Speakers: Donny Chen
record_10:
  Title: Modeling in Agile Agile
  Start time: 10/16/2013 13:00
  Stop time: 10/16/2013 14:00
  Room: ROOM 107
  Abstract: activity abstract
  Column span: '2'
  Position: '7'
  Row span: '2'
  Background color: ' - '
  Speakers: Kenji Hiranabe
record_11:
  Title: How to be an effective PO to Make Profitability in Maitenance Phase of CDMA
    Product?
  Start time: 10/16/2013 14:00
  Stop time: 10/16/2013 14:00
  Room: ROOM 101
  Abstract: activity abstract
  Column span: '2'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: Bin Hu
record_12:
  Title: Make agile adaption to our project
  Start time: 10/16/2013 14:00
  Stop time: 10/16/2013 14:00
  Room: ROOM 102
  Abstract: activity abstract
  Column span: '2'
  Position: '2'
  Row span: '2'
  Background color: ' - '
  Speakers: Bin Hu
record_13:
  Title: Shall I join an Agile Team?
  Start time: 10/16/2013 14:00
  Stop time: 10/16/2013 15:00
  Room: ROOM 103
  Abstract: activity abstract
  Column span: '2'
  Position: '3'
  Row span: '2'
  Background color: ' - '
  Speakers: Ariel HAN
record_14:
  Title: Continuous Deployment - To generate real business value through Lean and
    Agile practices
  Start time: 10/16/2013 14:00
  Stop time: 10/16/2013 15:00
  Room: ROOM 104
  Abstract: activity abstract
  Column span: '2'
  Position: '4'
  Row span: '2'
  Background color: ' - '
  Speakers: Deborah Chao
record_15:
  Title: Elegant automation test in agile
  Start time: 10/16/2013 14:00
  Stop time: 10/16/2013 15:00
  Room: ROOM 105
  Abstract: activity abstract
  Column span: '2'
  Position: '5'
  Row span: '2'
  Background color: ' - '
  Speakers: Lennart Allinger
record_16:
  Title: Art in Agile
  Start time: 10/16/2013 14:00
  Stop time: 10/16/2013 15:00
  Room: ROOM 106
  Abstract: activity abstract
  Column span: '2'
  Position: '6'
  Row span: '2'
  Background color: ' - '
  Speakers: Smilings Lu
record_17:
  Title: Applying Agile to Hardware Development
  Start time: 10/16/2013 14:00
  Stop time: 10/16/2013 15:00
  Room: ROOM 107
  Abstract: activity abstract
  Column span: '2'
  Position: '7'
  Row span: '2'
  Background color: ' - '
  Speakers: Clare Bao
record_18:
  Title: Tea Breaks
  Start time: 10/16/2013 15:00
  Stop time: 10/16/2013 15:30
  Abstract: activity abstract
  Column span: '7'
  Position: '1'
  Row span: '1'
  Background color: ' - '
  Speakers: Neil Johnson
record_19:
  Title: EEGS 3.0 with Agile (1st major CDMA release to follow Agile process at release
    level)
  Start time: 10/16/2013 15:30
  Stop time: 10/16/2013 16:30
  Room: ROOM 101
  Abstract: activity abstract
  Column span: '2'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: Maggie Cai
record_20:
  Title: A second thought on CPI Agile & CPI Process under F-model FRM
  Start time: 10/16/2013 15:30
  Stop time: 10/16/2013 16:30
  Room: ROOM 102
  Abstract: activity abstract
  Column span: '2'
  Position: '2'
  Row span: '2'
  Background color: ' - '
  Speakers: Robert Liu & Rocky Zhang R
record_21:
  Title: The power of being visible
  Start time: 10/16/2013 15:30
  Stop time: 10/16/2013 16:30
  Room: ROOM 103
  Abstract: activity abstract
  Column span: '2'
  Position: '3'
  Row span: '2'
  Background color: ' - '
  Speakers: Kevin Lin
record_22:
  Title: Continuous Integration ?it is a systematic product
  Start time: 10/16/2013 15:30
  Stop time: 10/16/2013 16:30
  Room: ROOM 104
  Abstract: activity abstract
  Column span: '2'
  Position: '4'
  Row span: '2'
  Background color: ' - '
  Speakers: Kecheng Wang
record_23:
  Title: Quality Control in Agile
  Start time: 10/16/2013 15:30
  Stop time: 10/16/2013 16:30
  Room: ROOM 105
  Abstract: activity abstract
  Column span: '2'
  Position: '5'
  Row span: '2'
  Background color: ' - '
  Speakers: Xiao Lei Jiang
record_24:
  Title: Marshmallow Challenge or Retrospective
  Start time: 10/16/2013 15:30
  Stop time: 10/16/2013 16:30
  Room: ROOM 106
  Abstract: activity abstract
  Column span: '2'
  Position: '6'
  Row span: '2'
  Background color: ' - '
  Speakers: Bob Jiang
record_25:
  Title: Retrospective
  Start time: 10/16/2013 15:30
  Stop time: 10/16/2013 16:30
  Room: ROOM 107
  Abstract: activity abstract
  Column span: '2'
  Position: '7'
  Row span: '2'
  Background color: ' - '
  Speakers: Linda Rising
record_26:
  Title: Porfolio Management in Agile
  Start time: 10/16/2013 16:30
  Stop time: 10/16/2013 17:30
  Room: ROOM 101
  Abstract: activity abstract
  Column span: '2'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: Jessica Pan
record_27:
  Title: Different cooperation models between Operative Product Owner and Scrum Master
  Start time: 10/16/2013 16:30
  Stop time: 10/16/2013 17:30
  Room: ROOM 102
  Abstract: activity abstract
  Column span: '2'
  Position: '2'
  Row span: '2'
  Background color: ' - '
  Speakers: Will Gao
record_28:
  Title: 'Agile People Management: 3 Reflective Questions '
  Start time: 10/16/2013 16:30
  Stop time: 10/16/2013 17:30
  Room: ROOM 103
  Abstract: activity abstract
  Column span: '2'
  Position: '3'
  Row span: '2'
  Background color: ' - '
  Speakers: Glen Wang
record_29:
  Title: A story of evolution -- CI journey in NDO SP & Deploy CI upon Legacy & Private
    Systems
  Start time: 10/16/2013 16:30
  Stop time: 10/16/2013 17:30
  Room: ROOM 104
  Abstract: activity abstract
  Column span: '2'
  Position: '4'
  Row span: '2'
  Background color: ' - '
  Speakers: Emily Geng & Ke Roy
record_30:
  Title: How CBA Component (TOF) Development Benefits from Agile
  Start time: 10/16/2013 16:30
  Stop time: 10/16/2013 17:30
  Room: ROOM 105
  Abstract: activity abstract
  Column span: '2'
  Position: '5'
  Row span: '2'
  Background color: ' - '
  Speakers: ' Sean Sun & Allen Zhao'
record_31:
  Title: Lean and Agile Clinic
  Start time: 10/16/2013 16:30
  Stop time: 10/16/2013 17:30
  Room: ROOM 106
  Abstract: activity abstract
  Column span: '2'
  Position: '6'
  Row span: '2'
  Background color: ' - '
  Speakers: Neil Johnson
record_32:
  Title: Exporing User Wish through Mindmapping
  Start time: 10/16/2013 16:30
  Stop time: 10/16/2013 17:30
  Room: ROOM 107
  Abstract: activity abstract
  Column span: '2'
  Position: '7'
  Row span: '2'
  Background color: ' - '
  Speakers: Kenji Hiranabe
record_33:
  Title: Open Space Topic Collection
  Start time: 10/17/2013 9:00
  Stop time: 10/17/2013 9:30
  Room: ' - '
  Abstract: ' - '
  Column span: '7'
  Position: '1'
  Row span: '1'
  Background color: ' - '
  Speakers: ' -'
record_34:
  Title: From Efficiency to Innovation
  Start time: 10/17/2013 9:30
  Stop time: 10/17/2013 10:30
  Room: Ballroom B
  Abstract: ' - '
  Column span: '7'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: Dieter Kaufhold
record_35:
  Title: Tea Break
  Start time: 10/17/2013 10:30
  Stop time: 10/17/2013 10:45
  Column span: '7'
  Position: '1'
  Row span: '1'
  Background color: ' - '
record_36:
  Title: I am the technica expert, and business man!
  Start time: 10/17/2013 10:45
  Stop time: 10/17/2013 11:45
  Room: ROOM 101
  Abstract: activity abstract
  Column span: '2'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: Arthur Wen
record_37:
  Title: 'Kanban? A better choice for our team & How LSV team Adapt Agile: from Scrum
    to Kanban'
  Start time: 10/17/2013 10:45
  Stop time: 10/17/2013 11:45
  Room: ROOM 102
  Abstract: activity abstract
  Column span: '2'
  Position: '2'
  Row span: '2'
  Background color: ' - '
  Speakers: Eric Dong & Sean Sun
record_38:
  Title: Continuous Learning
  Start time: 10/17/2013 10:45
  Stop time: 10/17/2013 11:45
  Room: ROOM 103
  Abstract: activity abstract
  Column span: '2'
  Position: '3'
  Row span: '2'
  Background color: ' - '
  Speakers: ' Sharon Li & Tomix Wen'
record_39:
  Title: How infrastructure shortens feedback loop in SGSN-MME
  Start time: 10/17/2013 10:45
  Stop time: 10/17/2013 11:45
  Room: ROOM 104
  Abstract: activity abstract
  Column span: '2'
  Position: '4'
  Row span: '2'
  Background color: ' - '
  Speakers: Alvin Hu
record_40:
  Title: Expediting Development With An Incremental Approach To Functional Verification
  Start time: 10/17/2013 10:45
  Stop time: 10/17/2013 11:45
  Room: ROOM 105
  Abstract: activity abstract
  Column span: '2'
  Position: '5'
  Row span: '2'
  Background color: ' - '
  Speakers: ' Sean Sun & Allen Zhao'
record_41:
  Title: Quality Management & TL9000 Compliance in Agile WoW
  Start time: 10/17/2013 10:45
  Stop time: 10/17/2013 11:45
  Room: ROOM 106
  Abstract: activity abstract
  Column span: '2'
  Position: '6'
  Row span: '2'
  Background color: ' - '
  Speakers: Neil Johnson
record_42:
  Title: Lean and Agile Clinic
  Start time: 10/17/2013 10:45
  Stop time: 10/17/2013 11:45
  Room: ROOM 107
  Abstract: activity abstract
  Column span: '2'
  Position: '7'
  Row span: '2'
  Background color: ' - '
  Speakers: Della Luo & Changying Sun
record_43:
  Title: Lunch
  Start time: 10/17/2013 11:45
  Stop time: 10/17/2013 13:00
  Column span: '7'
  Position: '1'
  Row span: '1'
  Background color: ' - '
record_44:
  Title: See the forest and trees - optimize the whole through integrated view
  Start time: 10/17/2013 13:00
  Stop time: 10/17/2013 14:00
  Room: ROOM 101
  Abstract: activity abstract
  Column span: '2'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: Bin Hu
record_45:
  Title: Practice of Scrum of Scrum
  Start time: 10/17/2013 13:00
  Stop time: 10/17/2013 14:00
  Room: ROOM 102
  Abstract: activity abstract
  Column span: '2'
  Position: '2'
  Row span: '2'
  Background color: ' - '
  Speakers: Ariel HAN
record_46:
  Title: Lead technical changes during agile deployment
  Start time: 10/17/2013 13:00
  Stop time: 10/17/2013 14:00
  Room: ROOM 103
  Abstract: activity abstract
  Column span: '2'
  Position: '3'
  Row span: '2'
  Background color: ' - '
  Speakers: Deborah Chao
record_47:
  Title: 'The practice of build cloud-based CI '
  Start time: 10/17/2013 13:00
  Stop time: 10/17/2013 14:00
  Room: ROOM 104
  Abstract: activity abstract
  Column span: '2'
  Position: '4'
  Row span: '2'
  Background color: ' - '
  Speakers: Lennart Allinger
record_48:
  Title: TDD on S/W
  Start time: 10/17/2013 13:00
  Stop time: 10/17/2013 14:00
  Room: ROOM 105
  Abstract: activity abstract
  Column span: '2'
  Position: '5'
  Row span: '2'
  Background color: ' - '
  Speakers: Smilings Lu
record_49:
  Title: The amazing journey of Agile transition for a verification team
  Start time: 10/17/2013 13:00
  Stop time: 10/17/2013 14:00
  Room: ROOM 106
  Abstract: activity abstract
  Column span: '2'
  Position: '6'
  Row span: '2'
  Background color: ' - '
  Speakers: Clare Bao
record_50:
  Title: Lean and Agile Clinic
  Start time: 10/17/2013 13:00
  Stop time: 10/17/2013 14:00
  Room: ROOM 107
  Abstract: activity abstract
  Column span: '2'
  Position: '7'
  Row span: '2'
  Background color: ' - '
  Speakers: Neil Johnson
record_51:
  Title: Visualization-A transparent window to the sunshine
  Start time: 10/17/2013 14:00
  Stop time: 10/17/2013 15:00
  Room: ROOM 101
  Abstract: activity abstract
  Column span: '2'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: Jessica Pan
record_52:
  Title: Lean Flow in Product Development
  Start time: 10/17/2013 14:00
  Stop time: 10/17/2013 15:00
  Room: ROOM 102
  Abstract: activity abstract
  Column span: '2'
  Position: '2'
  Row span: '2'
  Background color: ' - '
  Speakers: Will Gao
record_53:
  Title: Visualization-A transparent window to the sunshine
  Start time: 10/17/2013 14:00
  Stop time: 10/17/2013 15:00
  Room: ROOM 103
  Abstract: activity abstract
  Column span: '2'
  Position: '3'
  Row span: '2'
  Background color: ' - '
  Speakers: Glen Wang
record_54:
  Title: Conflict Management
  Start time: 10/17/2013 14:00
  Stop time: 10/17/2013 15:00
  Room: ROOM 104
  Abstract: activity abstract
  Column span: '2'
  Position: '4'
  Row span: '2'
  Background color: ' - '
  Speakers: Emily Geng & Ke Roy
record_55:
  Title: MSDP Continuous Integration and Testing system in BUSS CoE Service Enablement
  Start time: 10/17/2013 14:00
  Stop time: 10/17/2013 15:00
  Room: ROOM 105
  Abstract: activity abstract
  Column span: '2'
  Position: '5'
  Row span: '2'
  Background color: ' - '
  Speakers: Sean Sun & Allen Zhao
record_56:
  Title: TDD on S/W
  Start time: 10/17/2013 14:00
  Stop time: 10/17/2013 15:00
  Room: ROOM 106
  Abstract: activity abstract
  Column span: '2'
  Position: '6'
  Row span: '2'
  Background color: ' - '
  Speakers: Neil Johnson
record_57:
  Title: Practice to make team work happily with Agile/Kanban
  Start time: 10/17/2013 14:00
  Stop time: 10/17/2013 15:00
  Room: ROOM 107
  Abstract: activity abstract
  Column span: '2'
  Position: '7'
  Row span: '2'
  Background color: ' - '
  Speakers: undefined
record_58:
  Title: Tea Breaks
  Start time: 10/17/2013 15:00
  Stop time: 10/17/2013 15:30
  Room: ' - '
  Abstract: activity abstract
  Column span: '7'
  Position: '1'
  Row span: '1'
  Background color: ' - '
  Speakers: ' -'
record_59:
  Title: Drinking Lean from the Source
  Start time: 10/17/2013 15:30
  Stop time: 10/17/2013 16:40
  Room: Ballroom B
  Abstract: activity abstract
  Column span: '7'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: Kenji Hiranabe
record_60:
  Title: Closing
  Start time: 10/17/2013 16:40
  Stop time: 10/17/2013 17:30
  Room: Ballroom B
  Abstract: activity abstract
  Column span: '7'
  Position: '1'
  Row span: '2'
  Background color: ' - '
  Speakers: Peter Lundin, Lars Frank, Jane Tan, PDU IP OS, .
